# .github/workflows/auto-index-posts.yml
name: Auto-index new posts with IndexJump

on:
  push:
    paths:
      - 'src/content/posts/**/*.md'
    branches: 
      - main
      - master

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full git history
          
      - name: Wait for deployment
        run: sleep 45  # Give time for site to deploy after push
        
      - name: Trigger post indexing
        run: |
          response=$(curl -s -w "%{http_code}" \
            -X POST https://jonathanmwaniki.co.ke/api/index-posts \
            -H "Content-Type: application/json")
          
          http_code="${response: -3}"
          body="${response%???}"
          
          echo "Response code: $http_code"
          echo "Response body: $body"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Successfully processed posts"
          else
            echo "❌ Failed to process posts"
            exit 1
          fi